name: Build
on:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  integration_tests:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: shopware
        ports:
          - 3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '7.4' ]
        shopware_version: [ 'v6.4.8.1' ]
    name: Integration test - Php version ${{ matrix.php-version }} with Shopware ${{ matrix.shopware_version }}
    steps:
      - name: Install php
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl
      - name: Disable mysqldump column statistics
        run: echo 'column-statistics=0' | sudo tee -a /etc/mysql/conf.d/mysqldump.cnf
      - name: Checkout Shopware 6 code
        uses: actions/checkout@v2
        with:
          repository: shopware/development
          ref: ${{ matrix.shopware_version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: custom/plugins/MltisafeMultiSafepay
      - name: Install Shopware
        run: ./psh.phar init --DB_HOST="127.0.0.1" --DB_USER="root" --DB_PASSWORD="password" --DB_PORT=${{ job.services.mysql.ports['3306'] }}
      - name: Install Multisafepay dependencies
        working-directory: ./custom/plugins/MltisafeMultiSafepay
        #TODO: Add github/cache here
        run: composer install --no-dev
      - name: Install Multisafepay
        run: bin/console plugin:refresh && bin/console plugin:install -c --activate  MltisafeMultiSafepay
      - name: Initialize test databases
        run: ./psh.phar init-test-databases --DB_HOST="127.0.0.1" --DB_USER="root" --DB_PASSWORD="password" --DB_PORT=${{ job.services.mysql.ports['3306'] }}
      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration=./custom/plugins/MltisafeMultiSafepay/phpunit.xml.dist --coverage-clover=./custom/plugins/MltisafeMultiSafepay/coverage.xml
      - name: Send clover to codecov
        if: ${{ always() }}
        working-directory: ./custom/plugins/MltisafeMultiSafepay
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -R .
