name: Code sniffer
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: Code sniffer
    steps:
      - name: Install php dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          extensions: intl
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run Code sniffer
        run: vendor/bin/phpcs --standard=phpcs.ruleset.xml .
